const svg=path=>`<svg aria-hidden="true" viewBox="0 0 24 24"><path d="${path}"></path></svg>`;
const icons={dashboard:svg('M4 11.5 12 4l8 7.5V20h-5v-5H9v5H4Z'),tasks:svg('m5 12 4 4L19 6'),invoices:svg('M6 3h12v18H6Zm3 5h6M9 12h6M9 16h4'),orders:svg('M4 6h2l2 10h9l2-7H7m3 11h.01M17 20h.01'),contracts:svg('M6 3h9l3 3v15H6Zm8 0v4h4M9 12h6M9 16h6'),reports:svg('M5 20V10m5 10V4m5 16v-7m5 7V7')};
const navItems=[['dashboard','Dashboard'],['tasks','My tasks','8'],['invoices','Invoices','27'],['orders','Purchase orders','96'],['contracts','Contracts','8'],['reports','Reports']];
const invoices=[
  {id:'INV-20481',vendor:'Atlas Industrial Supply',amount:12480,status:'Manager approval',type:'approval',po:'4500821',match:98,due:'Apr 30, 2026',owner:'Alex Nguyen',lines:[['Industrial gearbox — Model X200',4,2450],['Mounting kit',4,320],['Freight',1,1400]]},
  {id:'INV-77821',vendor:'Precision Tools Co.',amount:3265,status:'Manager approval',type:'approval',po:'4500838',match:96,due:'May 4, 2026',owner:'Jordan Lee',lines:[['CNC tooling set',1,3265]]},
  {id:'INV-99314',vendor:'Summit Packaging',amount:8750,status:'PO exception',type:'exception',po:'4500792',match:72,due:'May 7, 2026',owner:'AP review',lines:[['Protective packaging',50,175]]},
  {id:'INV-66102',vendor:'Riverside Logistics',amount:960,status:'AP review',type:'match',po:'4500841',match:91,due:'May 12, 2026',owner:'Morgan Patel',lines:[['Regional freight',1,960]]},
  {id:'INV-55277',vendor:'Core Facility Services',amount:4320,status:'Manager approval',type:'approval',po:'4500770',match:100,due:'May 15, 2026',owner:'Alex Nguyen',lines:[['Quarterly maintenance',1,4320]]}
];
const state={view:'dashboard',selected:invoices[0],approved:new Set(),tour:-1,query:'',fieldsExpanded:false};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const workspace=document.querySelector('#workspace');

function renderNav(){document.querySelector('#nav').innerHTML=navItems.map(([id,label,badge])=>`<button class="nav-item ${state.view===id?'active':''}" data-view="${id}" aria-label="${label}"><span class="icon">${icons[id]}</span><span class="nav-label">${label}</span>${badge?`<span class="nav-badge">${badge}</span>`:''}</button>`).join('')}
function status(inv){const done=state.approved.has(inv.id);return `<span class="status ${done?'paid':inv.type}">${done?'Approved':inv.status}</span>`}
function filtered(){const q=state.query.toLowerCase().trim();return q?invoices.filter(i=>`${i.id} ${i.vendor} ${i.po}`.toLowerCase().includes(q)):invoices}
function queue(){const matches=filtered();return `<section class="panel queue-panel"><div class="panel-head"><h2>My task queue</h2><button class="link-button" data-view="tasks">All tasks</button></div><div class="task-summary">${[['8','Total'],['3','Approvals'],['2','Exceptions'],['3','Other']].map(x=>`<div class="summary-item"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div>${matches.length?`<ul class="queue">${matches.map(i=>`<li><button class="queue-item ${state.selected.id===i.id?'selected':''}" data-invoice="${i.id}"><strong>${i.vendor}</strong><span class="amount">${money(i.amount)}</span><small>${i.id}</small>${status(i)}</button></li>`).join('')}</ul>`:`<div class="empty"><h3>No matching invoices</h3><p>Try a vendor, invoice number, or purchase order.</p></div>`}</section>`}
function invoicePaper(inv){const subtotal=inv.lines.reduce((s,l)=>s+l[1]*l[2],0);return `<div class="invoice-paper"><div class="invoice-brand"><strong>ATLAS<span style="color:var(--success)">.</span></strong><span>INVOICE</span></div><div class="invoice-meta"><div><strong>${inv.vendor}</strong><p>1234 Commerce Drive</p><p>Riverton, IL 60611</p><br><strong>Bill to</strong><p>Northstar Manufacturing</p><p>1000 Production Way</p></div><dl><dt>Invoice no.</dt><dd>${inv.id}</dd><dt>Invoice date</dt><dd>Apr 2, 2026</dd><dt>Due date</dt><dd>${inv.due}</dd><dt>PO no.</dt><dd>${inv.po}</dd><dt>Terms</dt><dd>Net 30</dd></dl></div><table class="line-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>${inv.lines.map(l=>`<tr><td>${l[0]}</td><td>${l[1]}</td><td>${money(l[2])}</td><td>${money(l[1]*l[2])}</td></tr>`).join('')}</tbody></table><div class="totals"><div><span>Subtotal</span><span>${money(subtotal)}</span></div><div><span>Tax & fees</span><span>${money(inv.amount-subtotal)}</span></div><div class="grand"><span>Total</span><span>${money(inv.amount)}</span></div></div></div>`}
function invoicePanel(inv){return `<section class="panel invoice-panel"><div class="invoice-head"><div><button class="link-button" data-view="invoices">← Invoices</button><h2>${inv.vendor}</h2><p>${inv.id}</p><div class="chip-row"><span class="status match">Match ${inv.match}%</span>${status(inv)}</div></div><div class="invoice-total"><strong>${money(inv.amount)}</strong><small>Due ${inv.due}</small></div></div>${invoicePaper(inv)}</section>`}
function relay(inv){const approved=state.approved.has(inv.id);const fields=[['Vendor',inv.vendor],['Invoice number',inv.id],['Due date',inv.due],['PO number',inv.po],['Total amount',money(inv.amount)],...(state.fieldsExpanded?[['Invoice date','Apr 2, 2026'],['Payment terms','Net 30'],['Currency','USD']]:[])];return `<div class="stack right-stack"><section class="panel"><div class="panel-head"><h3>Approval relay</h3><button class="link-button" data-action="tour">View process</button></div><div class="relay"><div class="relay-step done"><span class="relay-mark"></span><div><strong>Capture complete</strong><small>Invoice received and fields extracted</small></div></div><div class="relay-step done"><span class="relay-mark"></span><div><strong>AP review complete</strong><small>Matched to PO ${inv.po}</small></div></div><div class="relay-step ${approved?'done':'active'}"><span class="relay-mark"></span><div><strong>${approved?'Manager approved':'Manager approval'}</strong><small>${approved?'Approved by Alex Nguyen':'Your approval is required'}</small></div></div><div class="relay-step ${approved?'active':''}"><span class="relay-mark"></span><div><strong>Payment scheduled</strong><small>${approved?'Ready for ERP export':'Sent to ERP after approval'}</small></div></div><button class="primary-button full" data-action="approve" ${approved?'disabled':''}>${approved?'Invoice approved':'Review and approve'}</button></div></section><section class="panel"><div class="panel-head"><h3>Extracted fields</h3><button class="link-button" data-action="fields">${state.fieldsExpanded?'Show less':'View all'}</button></div><div class="evidence">${fields.map(r=>`<div class="evidence-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>PO match</h3><span class="status match">${inv.match}%</span></div><div class="evidence">${[['PO number',inv.po],['Matched amount',money(inv.amount)],['Variance',inv.match===100?'$0.00':'Review confidence'],['Coding','6410 · Machinery & Equipment']].map(r=>`<div class="evidence-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')}</div></section></div>`}
function dashboard(){workspace.innerHTML=`<div class="workspace-grid">${queue()}${invoicePanel(state.selected)}${relay(state.selected)}</div>`}
function tablePage(kind){const titles={tasks:['My tasks','Everything currently waiting for action.'],invoices:['Invoices','Captured invoices, match status, and approval ownership in one place.'],orders:['Purchase orders','Committed spend and delivery status from the connected ERP.'],contracts:['Contracts','Active agreements and the invoices governed by them.']};const [title,copy]=titles[kind];let rows=kind==='orders'?invoices.map(i=>[i.po,i.vendor,money(i.amount),'Delivered',i.match+'% matched']):kind==='contracts'?invoices.slice(0,4).map((i,n)=>['CT-2026-0'+(n+1),i.vendor,'Active','Dec 31, 2026',money(i.amount*4)]):filtered().map(i=>[i.id,i.vendor,money(i.amount),i.po,state.approved.has(i.id)?'Approved':i.status]);const heads=kind==='orders'?['Purchase order','Vendor','Committed','Delivery','Invoice status']:kind==='contracts'?['Contract','Partner','Status','Renewal','Annual value']:['Invoice','Vendor','Amount','Purchase order','Status'];workspace.innerHTML=`<div class="page-intro"><div><h2>${title}</h2><p>${copy}</p></div><button class="primary-button" data-action="tour">Show me how it works</button></div><section class="panel table-wrap">${rows.length?`<table class="data-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr ${String(r[0]).startsWith('INV')?`data-invoice="${r[0]}" tabindex="0" role="link" aria-label="Open ${r[0]} from ${r[1]}"`:''}>${r.map((c,n)=>`<td>${n===heads.length-1?`<span class="status ${String(c).includes('Exception')?'exception':'match'}">${c}</span>`:c}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="empty"><h3>No matching results</h3><p>Try an invoice number, vendor, or purchase order.</p></div>`}</section>`}
function reports(){workspace.innerHTML=`<div class="page-intro"><div><h2>AP performance</h2><p>A synthetic view of invoice throughput, exceptions, and approval speed.</p></div><button class="primary-button" data-action="export">Download synthetic CSV</button></div><div class="report-grid"><section class="panel"><div class="panel-head"><h3>Invoices processed</h3><span>Last 6 months</span></div><div class="chart">${[54,66,58,81,74,92].map((v,i)=>`<div class="bar" style="height:${v}%"><span>${['Nov','Dec','Jan','Feb','Mar','Apr'][i]}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h3>Operational health</h3></div><div class="metric-list">${[['94%','touchless match'],['1.8 days','approval cycle'],['3.2%','exception rate'],['100%','audit trail coverage']].map(x=>`<div class="metric"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div></section></div>`}
function render(){renderNav();document.querySelector('#page-title').textContent=state.view==='dashboard'?'Good morning, Alex':navItems.find(x=>x[0]===state.view)?.[1]||'Rillion';if(state.view==='dashboard')dashboard();else if(state.view==='reports')reports();else tablePage(state.view)}
const tours=[['Start with the work queue','Rillion brings approvals, matching exceptions, and AP review into one prioritized queue.','dashboard'],['See the invoice evidence','Select any invoice to compare the source document, extracted fields, PO match, and coding.','dashboard'],['Follow the approval relay','The right rail shows what completed, who owns the next decision, and what happens after approval.','dashboard'],['Measure the operation','Reports summarize throughput, approval time, and exception rates without exposing live customer data.','reports']];
function showTour(){const t=tours[state.tour];document.querySelector('#tour').hidden=false;document.querySelector('#tour-count').textContent=`${state.tour+1} of ${tours.length}`;document.querySelector('#tour-title').textContent=t[0];document.querySelector('#tour-copy').textContent=t[1];state.view=t[2];render()}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function downloadReport(){const csv='Metric,Value\nTouchless match,94%\nApproval cycle,1.8 days\nException rate,3.2%\nAudit trail coverage,100%\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=Object.assign(document.createElement('a'),{href:url,download:'rillion-synthetic-ap-report.csv'});a.click();URL.revokeObjectURL(url);toast('Synthetic report downloaded')}
function openInvoice(id){state.selected=invoices.find(i=>i.id===id)||state.selected;state.fieldsExpanded=false;state.view='dashboard';render()}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]')?.dataset.view;const id=e.target.closest('[data-invoice]')?.dataset.invoice;const action=e.target.closest('[data-action]')?.dataset.action;if(view){state.view=view;render();return}if(id){openInvoice(id);return}if(action==='approve'){state.approved.add(state.selected.id);render();toast(`${state.selected.id} approved and ready for payment`)}if(action==='fields'){state.fieldsExpanded=!state.fieldsExpanded;render()}if(action==='reset'){state.approved.clear();state.selected=invoices[0];state.fieldsExpanded=false;state.view='dashboard';state.query='';document.querySelector('#search').value='';render();toast('Demo reset')}if(action==='tour'){state.tour=0;showTour()}if(action==='tour-next'){state.tour++;if(state.tour>=tours.length){document.querySelector('#tour').hidden=true;state.tour=-1;toast('Tour complete — explore anything')}else showTour()}if(action==='tour-close'){document.querySelector('#tour').hidden=true;state.tour=-1}if(action==='export')downloadReport()});
document.addEventListener('keydown',e=>{const row=e.target.closest('tr[data-invoice]');if(row&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openInvoice(row.dataset.invoice)}});
document.querySelector('#search').addEventListener('input',e=>{state.query=e.target.value;if(state.view!=='dashboard'&&state.view!=='invoices'&&state.view!=='tasks')state.view='invoices';render()});
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(navItems.some(x=>x[0]===view)){state.view=view;render()}});
render();
